VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  (1..3).each do |i|
    config.vm.define "etcd-node-#{i}" do |node|
      node.vm.box = "bento/ubuntu-20.04"
      node.vm.hostname = "etcd-node-#{i}"
      node.vm.network "private_network", ip: "192.168.56.10#{i}"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end

      node.vm.boot_timeout = 600
      node.ssh.forward_agent = false

      node.vm.provision "shell", path: "bootstrap-etcd.sh", args: "#{i}"
    end
  end
end
